spring.application.name=searchservice
spring.datasource.url=jdbc:postgresql://localhost:5432/places
spring.datasource.username=research
spring.datasource.password=researchUserPassword
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=5741

#Profile
spring.profiles.active=retry-async

#Prometheus
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

#Resilience4j
resilience4j.retry.instances.searchRetry.max-attempts=3
resilience4j.retry.instances.searchRetry.wait-duration=200ms
resilience4j.retry.instances.searchRetry.enable-exponential-backoff=true
resilience4j.retry.instances.searchRetry.exponential-backoff-multiplier=2
resilience4j.retry.instances.searchRetry.enable-randomized-wait=true
resilience4j.retry.instances.searchRetry.randomized-wait-factor=0.5
resilience4j.timelimiter.instances.searchTimeout.timeout-duration=1s